### STRUCTURAL DATA VALIDATION

In [1]:
import pandas as pd

original_df = pd.read_csv("itunes_music_dataset.csv")

In [2]:
raw_df = original_df

In [3]:
raw_df

,track_id,track_name,artist_name,collection_name,album_artist,genre,rating,track_price,collection_price,release_date,track_time_millis,country,currency,preview_url,artwork_url
0,1624932774,POP!,NAYEON,IM NAYEON,NaN,Dance,Clean,1.29,6.99,2022-06-24T12:00:00Z,168107.0,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
1,1022164261,Riptide,Vance Joy,Dream Your Life Away (Special Edition),NaN,Alternative,Clean,1.29,9.99,2013-03-22T07:00:00Z,202019.0,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
2,1207120448,Something Just Like This,The Chainsmokers & Coldplay,Memories...Do Not Open,The Chainsmokers,Dance,Clean,1.29,9.99,2017-02-22T08:00:00Z,247165.0,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
3,1369380479,lovely,Billie Eilish & Khalid,lovely - Single,NaN,Pop,Clean,1.29,1.29,2018-04-19T12:00:00Z,200187.0,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4,1450695872,when the party's over,Billie Eilish,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",NaN,Alternative,Clean,1.29,10.99,2018-10-17T07:00:00Z,196077.0,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4909,712330693,I Got 5 On It (feat. Michael Marshall),Luniz,Operation Stackola,NaN,Hip-Hop/Rap,Clean,1.29,7.99,1995-05-23T07:00:00Z,253533.0,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4910,1817490073,Dekh Lo Awaz Dekar (Prem Geet / Soundtrack Ver...,Anuradha Paudwal,Old Hindi Songs - Vol.2,Kishore Kumar & Asha Bhosle,Soundtrack,Clean,NaN,NaN,1981-01-01T12:00:00Z,355067.0,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4911,1817490077,Khwabon Ko (Prem Geet / Soundtrack Version),Suresh Wadkar,Old Hindi Songs - Vol.2,Kishore Kumar & Asha Bhosle,Soundtrack,Clean,NaN,NaN,1981-01-01T12:00:00Z,232027.0,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4912,1817490076,"Suhani Sham Aayi Hai (From ""Shaukeeen"")",Asha Bhosle & R.D. Burman,Old Hindi Songs - Vol.2,Kishore Kumar & Asha Bhosle,Soundtrack,Clean,NaN,NaN,1982-01-01T12:00:00Z,283403.0,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4913,1817507850,"Mujhe Tadpati Rahi (From ""Damaad"")",Asha Bhosle & Mohd. Rafi,Old Hindi Songs - Vol.1,Kishore Kumar,Soundtrack,Clean,NaN,NaN,2007-05-07T12:00:00Z,300747.0,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...

In [4]:
print(raw_df.columns)
(raw_df.shape)

Index(['track_id', 'track_name', 'artist_name', 'collection_name',
       'album_artist', 'genre', 'rating', 'track_price', 'collection_price',
       'release_date', 'track_time_millis', 'country', 'currency',
       'preview_url', 'artwork_url'],
      dtype='object')

(4914, 15)

In [5]:
raw_df.dtypes

track_id               int64
track_name            object
artist_name           object
collection_name       object
album_artist          object
genre                 object
rating                object
track_price           object
collection_price      object
release_date          object
track_time_millis    float64
country               object
currency              object
preview_url           object
artwork_url           object
dtype: object

In [6]:
raw_df.columns

Index(['track_id', 'track_name', 'artist_name', 'collection_name',
       'album_artist', 'genre', 'rating', 'track_price', 'collection_price',
       'release_date', 'track_time_millis', 'country', 'currency',
       'preview_url', 'artwork_url'],
      dtype='object')

removing unnecessory columns

In [7]:
raw_df = raw_df.drop(['album_artist', 'currency', 'preview_url', 'artwork_url'], axis=1)
df = raw_df

In [8]:
df.head()

,track_id,track_name,artist_name,collection_name,genre,rating,track_price,collection_price,release_date,track_time_millis,country
0,1624932774,POP!,NAYEON,IM NAYEON,Dance,Clean,1.29,6.99,2022-06-24T12:00:00Z,168107.0,USA
1,1022164261,Riptide,Vance Joy,Dream Your Life Away (Special Edition),Alternative,Clean,1.29,9.99,2013-03-22T07:00:00Z,202019.0,USA
2,1207120448,Something Just Like This,The Chainsmokers & Coldplay,Memories...Do Not Open,Dance,Clean,1.29,9.99,2017-02-22T08:00:00Z,247165.0,USA
3,1369380479,lovely,Billie Eilish & Khalid,lovely - Single,Pop,Clean,1.29,1.29,2018-04-19T12:00:00Z,200187.0,USA
4,1450695872,when the party's over,Billie Eilish,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",Alternative,Clean,1.29,10.99,2018-10-17T07:00:00Z,196077.0,USA

In [9]:
df['country'].nunique()

1

In [10]:
df['country'].value_counts()

country
USA    4913
Name: count, dtype: int64

country column  contains only one unique value (USA)
So removing country column

In [11]:
df = df.drop(['country'], axis=1)

In [12]:
df.columns

Index(['track_id', 'track_name', 'artist_name', 'collection_name', 'genre',
       'rating', 'track_price', 'collection_price', 'release_date',
       'track_time_millis'],
      dtype='object')

BY removing 5 columns Our data diamensions has changed

In [13]:
df.shape

(4914, 10)

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
df.head()

,track_id,track_name,artist_name,collection_name,genre,rating,track_price,collection_price,release_date,track_time_millis
0,1624932774,POP!,NAYEON,IM NAYEON,Dance,Clean,1.29,6.99,2022-06-24T12:00:00Z,168107.0
1,1022164261,Riptide,Vance Joy,Dream Your Life Away (Special Edition),Alternative,Clean,1.29,9.99,2013-03-22T07:00:00Z,202019.0
2,1207120448,Something Just Like This,The Chainsmokers & Coldplay,Memories...Do Not Open,Dance,Clean,1.29,9.99,2017-02-22T08:00:00Z,247165.0
3,1369380479,lovely,Billie Eilish & Khalid,lovely - Single,Pop,Clean,1.29,1.29,2018-04-19T12:00:00Z,200187.0
4,1450695872,when the party's over,Billie Eilish,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",Alternative,Clean,1.29,10.99,2018-10-17T07:00:00Z,196077.0

### Structural validation completed here
-----x------

### DATA TYPE CORRECTION

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df.dtypes

track_id               int64
track_name            object
artist_name           object
collection_name       object
genre                 object
rating                object
track_price           object
collection_price      object
release_date          object
track_time_millis    float64
dtype: object

Converting track_id to string ,   
Converting release_date to datetime,  
Converting rating to numeric

In [18]:
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')
# df['rating'] = pd.to_numeric(df['rating'])
df['track_id'] = df['track_id'].astype(str)

In [19]:
df['rating'].value_counts()

rating
Clean     4913
227196       1
Name: count, dtype: int64

Here we found rating has only one value So we need to drop this column

In [20]:
df = df.drop(['rating'], axis=1)

In [21]:
print(df.columns)
df.shape

Index(['track_id', 'track_name', 'artist_name', 'collection_name', 'genre',
       'track_price', 'collection_price', 'release_date', 'track_time_millis'],
      dtype='object')

(4914, 9)

In [22]:
df.dtypes

track_id                          object
track_name                        object
artist_name                       object
collection_name                   object
genre                             object
track_price                       object
collection_price                  object
release_date         datetime64[ns, UTC]
track_time_millis                float64
dtype: object

##### Type correction done ----x------

#### MISSING VALUE check

In [23]:
df.isna().sum()

track_id               0
track_name             0
artist_name            2
collection_name        0
genre                  0
track_price          375
collection_price     376
release_date          49
track_time_millis      1
dtype: int64

In [24]:
df[['track_price','collection_price','track_time_millis','release_date']].describe()

       track_time_millis
count       4.913000e+03
mean        2.395843e+05
std         1.206409e+05
min         3.050300e+04
25%         1.936030e+05
50%         2.266810e+05
75%         2.690320e+05
max         4.676058e+06

In [25]:
# Replace -1 with NaN
df['track_price'] = df['track_price'].replace(-1, pd.NA)
df['collection_price'] = df['collection_price'].replace(-1, pd.NA)

# Check again
df[['track_price','collection_price']].describe()
df[['track_price','collection_price']].isnull().sum()

track_price         375
collection_price    376
dtype: int64

In [26]:
df[['track_price','collection_price']].describe()

       track_price collection_price
count         4539             4538
unique           5               61
top           1.29             9.99
freq          3461             1267

In [27]:
df[['track_price','collection_price','track_time_millis','release_date']].isnull().sum()

track_price          375
collection_price     376
track_time_millis      1
release_date          49
dtype: int64

Checking If duplicated rows present

In [28]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4909    False
4910    False
4911    False
4912    False
4913    False
Length: 4914, dtype: bool

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4914 entries, 0 to 4913
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   track_id           4914 non-null   object
 1   track_name         4914 non-null   object
 2   artist_name        4912 non-null   object
 3   collection_name    4914 non-null   object
 4   genre              4914 non-null   object
 5   track_price        4539 non-null   object
 6   collection_price   4538 non-null   object
 7   release_date       4865 non-null   datetime64[ns, UTC]
 8   track_time_millis  4913 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(1), object(7)
memory usage: 345.6+ KB

there are 4 columns having missing values.

* **artist_name (2 missing)** → Very small number. It won’t affect the analysis.

* **track_price & collection_price (~8% missing)** → We don’t want to guess or fill prices because that would create fake data. We can analyze prices using the available values only.

* **release_date (1% missing)** → Very few missing, and we can ignore them when doing time-based analysis.

In short:
The missing values are either very small in number or should not be filled because it would create incorrect data.

In [30]:
df.to_csv('itunes_music_cleaned_data.csv', index=False)

Cleaned CSV file extracted successfully